# AALS System Configuration
# This is the default configuration file for the AALS system
# Environment-specific overrides should be placed in environment-specific files

system:
  name: "AALS"
  version: "0.1.0"
  environment: "development"  # development, staging, production
  debug: true
  log_level: "INFO"

# Database Configuration
database:
  # PostgreSQL connection (used for structured data)
  postgres:
    host: "localhost"
    port: 5432
    database: "aals"
    username: "aals_user"
    password: ""  # Set via environment variable AALS_DB_PASSWORD
    
  # Redis connection (used for caching and sessions)
  redis:
    host: "localhost"
    port: 6379
    database: 0
    password: ""  # Set via environment variable AALS_REDIS_PASSWORD

# Module Configuration
modules:
  # Module 1: Config Manager (always enabled)
  config_manager:
    enabled: true
    
  # Module 2: Slack Alert Reader
  slack_alert_reader:
    enabled: true
    channels: ["#alerts", "#incidents", "#monitoring"]
    max_messages: 100  # 最大取得メッセージ数
    lookback_hours: 24  # 過去何時間分を取得
    alert_keywords: ["CRITICAL", "WARNING", "ERROR", "DOWN", "FAILED"]
    cache_ttl_seconds: 300  # キャッシュ有効時間（5分）
    
  # Module 3: Basic Logger
  basic_logger:
    enabled: true
    # アプリケーションログ設定
    app_log:
      file: "logs/aals.log"
      level: "INFO"
      max_file_size: "10MB"
      backup_count: 5
      format: "json"  # json or text
    # 監査ログ設定  
    audit_log:
      file: "logs/audit.log"
      level: "INFO"
      max_file_size: "50MB"
      backup_count: 10
      format: "json"
      # 監査ログの保持期間（日数）
      retention_days: 90
    # コンソール出力設定
    console:
      enabled: true
      level: "INFO" 
      format: "text"  # development時は見やすいテキスト形式
      colorize: true
    # 開発モード設定
    development:
      detailed_traceback: true
      log_sql_queries: false
      log_api_requests: true
    
  # Module 4: Prometheus Analyzer
  prometheus_analyzer:
    enabled: true
    url: "http://localhost:9090"  # Prometheus server URL
    timeout: 30  # HTTP timeout in seconds
    # Threshold configuration for alerts
    thresholds:
      cpu_warning: 70.0      # CPU usage % warning
      cpu_critical: 90.0     # CPU usage % critical
      memory_warning: 80.0   # Memory usage % warning  
      memory_critical: 95.0  # Memory usage % critical
      disk_warning: 85.0     # Disk usage % warning
      disk_critical: 95.0    # Disk usage % critical
      load_warning: 4.0      # Load average warning
      load_critical: 8.0     # Load average critical
      response_warning: 2.0  # HTTP response time warning (seconds)
      response_critical: 5.0 # HTTP response time critical (seconds)
    # Query configuration
    default_step: "1m"       # Default step for range queries
    max_history_hours: 24    # Maximum hours of historical data
    
  # Module 5: GitHub Issues Searcher
  github_issues_searcher:
    enabled: true
    token: ""  # AALS_GITHUB_TOKEN - GitHub Personal Access Token
    repositories: ["owner/repo1", "owner/repo2"]  # Default repositories to search
    timeout: 30  # HTTP timeout in seconds
    max_results: 50  # Maximum issues to fetch per repository
    similarity_threshold: 0.3  # Minimum similarity score for issues to be considered similar
    search_config:
      include_closed: true  # Include closed issues in search
      max_age_days: 365  # Maximum age of issues to consider (days)
      priority_keywords:
        critical: ["critical", "urgent", "emergency", "production down", "outage"]
        high: ["high", "important", "blocker", "security breach"]
        medium: ["medium", "bug", "performance"]
        low: ["low", "enhancement", "documentation"]
    
  # Module 6: LLM Wrapper
  llm_wrapper:
    enabled: true
    # Default provider configuration
    default_provider: "claude"  # claude, openai, azure
    timeout: 60  # HTTP timeout in seconds
    max_retries: 3  # Maximum retry attempts
    retry_delay: 1  # Delay between retries (seconds)
    
    # Provider-specific configurations
    providers:
      claude:
        enabled: true
        api_key: ""  # AALS_CLAUDE_API_KEY
        model: "claude-3-haiku-20240307"  # Default model
        max_tokens: 4096
        temperature: 0.1  # Low temperature for consistent responses
        base_url: "https://api.anthropic.com"
        
      openai:
        enabled: false
        api_key: ""  # AALS_OPENAI_API_KEY
        model: "gpt-4"
        max_tokens: 4096
        temperature: 0.1
        base_url: "https://api.openai.com/v1"
        
    # Response caching configuration
    cache:
      enabled: true
      ttl_seconds: 3600  # 1 hour cache for similar queries
      max_entries: 1000  # Maximum cached entries
      
    # Prompt templates and system messages
    system_prompts:
      incident_analysis: |
        You are an expert Site Reliability Engineer (SRE) assistant. 
        Analyze the provided incident data and provide actionable insights.
        Focus on:
        1. Root cause identification
        2. Immediate mitigation steps
        3. Prevention strategies
        4. Related patterns or similar incidents
        
      metric_analysis: |
        You are a systems monitoring expert. 
        Analyze the provided metrics and alert data.
        Provide clear assessment of:
        1. Current system health
        2. Trending issues
        3. Performance bottlenecks
        4. Recommended actions
        
      solution_generation: |
        You are a technical troubleshooting expert.
        Based on the provided issue description and context, generate:
        1. Step-by-step troubleshooting guide
        2. Common solutions for this type of issue
        3. Escalation recommendations
        4. Preventive measures

# Security Configuration
security:
  # API Keys and secrets (set via environment variables)
  secret_key: ""  # AALS_SECRET_KEY
  
  # Rate limiting
  rate_limit:
    enabled: true
    requests_per_minute: 60
    
  # Audit logging
  audit:
    enabled: true
    log_file: "logs/audit.log"

# Integration Configuration (populated as modules are implemented)
integrations:
  slack:
    token: ""  # AALS_SLACK_TOKEN
    
  github:
    token: ""  # AALS_GITHUB_TOKEN
    
  prometheus:
    endpoints: []
    
  llm:
    claude_api_key: ""  # AALS_CLAUDE_API_KEY
    openai_api_key: ""  # AALS_OPENAI_API_KEY
    
  ssh:
    key_file: ""
    known_hosts_file: ""

# Development/Testing Configuration
development:
  auto_reload: true
  mock_external_apis: false
  test_data_dir: "tests/fixtures"